; BACKGROUND_TILES.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Background_Tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 5
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

SECTION "Background_Tiles", rom0

; Start of tile array.
BackgroundTiles::
DB $28,$28,$50,$50,$40,$40,$40,$48
DB $80,$BD,$98,$FF,$68,$6F,$07,$07
DB $00,$00,$00,$00,$01,$01,$02,$02
DB $04,$04,$08,$08,$08,$08,$08,$08
DB $00,$00,$60,$60,$98,$98,$04,$04
DB $05,$05,$02,$02,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $E0,$E0,$10,$10,$08,$08,$04,$04
DB $00,$00,$00,$00,$00,$00,$00,$03
DB $01,$D7,$02,$FE,$C4,$FC,$38,$38
DB $02,$02,$01,$07,$01,$4F,$06,$DE
DB $C8,$F8,$30,$30,$00,$00,$00,$00
BackgroundTilesEnd::

; End of BACKGROUND_TILES.Z80
