; CACTUS_TILES.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Cactus_Tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 6
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

SECTION "Cactus_Tiles", rom0

; Start of tile array.
CactusTiles::
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $6F,$33,$14,$1B,$2F,$08,$1F,$1F
DB $10,$1F,$1F,$1F,$08,$0F,$07,$07
DB $00,$00,$0A,$00,$07,$07,$1B,$0C
DB $57,$18,$3F,$24,$7B,$26,$3F,$20
DB $30,$3F,$10,$1F,$08,$0F,$0C,$0F
DB $03,$03,$01,$00,$01,$00,$01,$00
DB $0F,$0F,$30,$3F,$40,$7F,$42,$7F
DB $80,$FF,$82,$FF,$C1,$FF,$40,$7F
DB $3B,$2A,$57,$12,$03,$02,$0F,$0F
DB $08,$0F,$0F,$0F,$04,$07,$07,$07
DB $00,$04,$01,$03,$06,$07,$07,$04
DB $17,$06,$1D,$1E,$7F,$20,$3F,$2E
CactusTilesEnd::

; End of CACTUS_TILES.Z80
