INCLUDE "hardware.inc"
INCLUDE "macro.inc"
INCLUDE "enemyConstants.inc"

LEVEL_UPDATE_REFRESH_TIME EQU %00001111
LEVEL_WAIT_END_COUNTER EQU 1

; Common Spawning Coordinates
OFFSCREEN_TOP EQU 0
OFFSCREEN_BOTTOM EQU 156
OFFSCREEN_LEFT EQU 0
OFFSCREEN_RIGHT EQU SCRN_X
MIDDLE_SCREEN EQU 72

SPAWN_Y_A EQU 28
SPAWN_Y_B EQU 56
SPAWN_Y_C EQU 84
SPAWN_Y_D EQU 112
SPAWN_X_A EQU 32
SPAWN_X_B EQU 64
SPAWN_X_C EQU 96
SPAWN_X_D EQU 128

SECTION "level vars", WRAM0
    wLevel:: DB
    wLevelWaitCounter:: DB
    wLevelWaitBoss:: DB
    wLevelDataAddress:: DS 2
    wLevelWaitEndCounter:: DB

SECTION "level data", ROM0

; LEVEL INSTRUCTIONS *************************************

; City Levels

Level1:
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_C, EASY
    LEVEL_WAIT 8
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_B, MEDIUM
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_A, EASY
    LEVEL_WAIT 8
    LEVEL_SPAWN BALLOON_CARRIER, SPAWN_Y_C - 8, OFFSCREEN_RIGHT, NONE
    LEVEL_WAIT 8
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_D, EASY
    LEVEL_WAIT 4
    LEVEL_SPAWN BOMB, OFFSCREEN_BOTTOM, SPAWN_X_A, EASY
    LEVEL_WAIT 6
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_A, MEDIUM
    LEVEL_WAIT 1
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_B, EASY
    LEVEL_WAIT 2
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_D, HARD
    LEVEL_WAIT 8
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_B, EASY
    LEVEL_WAIT 6
    LEVEL_SPAWN BOMB, OFFSCREEN_BOTTOM, SPAWN_X_B, EASY
    LEVEL_WAIT 8
    LEVEL_SPAWN BALLOON_CARRIER, SPAWN_Y_A, OFFSCREEN_LEFT, NONE
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_D, EASY
    LEVEL_SPAWN BALLOON_CARRIER, SPAWN_Y_C, OFFSCREEN_RIGHT, FOLLOW_VARIANT
    LEVEL_WAIT 4
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_A, EASY
    LEVEL_WAIT 8
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_B, EASY
    LEVEL_WAIT 2
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_C, EASY
    LEVEL_WAIT 2
    LEVEL_SPAWN BOMB, OFFSCREEN_BOTTOM, SPAWN_X_D, EASY
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_C, EASY
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_B, EASY
    LEVEL_WAIT 4
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM + 2, SPAWN_X_A, EASY
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM - 6, SPAWN_X_D, EASY
    LEVEL_SPAWN BOMB, OFFSCREEN_BOTTOM + 4, SPAWN_X_B - 4, EASY
    LEVEL_SPAWN BOMB, OFFSCREEN_BOTTOM - 12, SPAWN_X_C + 4, EASY
    LEVEL_WAIT 6
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_B - 2, MEDIUM
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_B - 16, MEDIUM
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_A + 2, MEDIUM
    LEVEL_SPAWN BALLOON_CARRIER, SPAWN_Y_C + 8, OFFSCREEN_LEFT, FOLLOW_VARIANT
    LEVEL_WAIT 4
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_C + 2, MEDIUM
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_C + 16, MEDIUM
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_D - 2, MEDIUM
    LEVEL_SPAWN BALLOON_CARRIER, SPAWN_Y_D - 8, OFFSCREEN_RIGHT, FOLLOW_VARIANT
    LEVEL_WAIT 4
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_C - 6, MEDIUM
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_C - 19, MEDIUM
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_B - 3, MEDIUM
    LEVEL_SPAWN BOMB, OFFSCREEN_BOTTOM, SPAWN_X_B - 19, EASY
    LEVEL_WAIT 4
    LEVEL_SPAWN BALLOON_CARRIER, SPAWN_Y_B + 4, OFFSCREEN_LEFT, NONE
    LEVEL_SPAWN BALLOON_CARRIER, SPAWN_Y_A, OFFSCREEN_RIGHT, NONE
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_A, EASY
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_D, EASY
    LEVEL_WAIT 4
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_B + 8, HARD
    LEVEL_WAIT 2
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_C, HARD
    LEVEL_SPAWN BALLOON_CARRIER, SPAWN_Y_B, OFFSCREEN_LEFT, FOLLOW_VARIANT
    LEVEL_WAIT 3
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_B + 16, MEDIUM
    LEVEL_SPAWN BOMB, OFFSCREEN_BOTTOM, SPAWN_X_B + 32, EASY
    LEVEL_SPAWN BOMB, OFFSCREEN_BOTTOM, SPAWN_X_B, EASY
    LEVEL_WAIT 16
    ; TODO maybe add a firework that would just simply animate!
    LEVEL_END
    
Level2:
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_C, MEDIUM
    LEVEL_WAIT 2
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_B + 6, MEDIUM
    LEVEL_SPAWN BALLOON_CARRIER, SPAWN_Y_B - 8, OFFSCREEN_LEFT, NONE
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_D + 8, EASY
    LEVEL_SPAWN BALLOON_CARRIER, SPAWN_Y_A, OFFSCREEN_RIGHT, NONE
    LEVEL_WAIT 4
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, 76, HARD
    LEVEL_WAIT 8
    LEVEL_SPAWN BALLOON_CARRIER, SPAWN_Y_B + 16, OFFSCREEN_RIGHT + 4, NONE
    LEVEL_SPAWN BALLOON_CARRIER, SPAWN_Y_B - 18, OFFSCREEN_RIGHT, NONE
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_C + 6, MEDIUM
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_B + 6, MEDIUM
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_A + 6, MEDIUM
    LEVEL_WAIT 4
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, 76, EASY
    LEVEL_WAIT 4
    LEVEL_SPAWN BALLOON_CARRIER, SPAWN_Y_B, OFFSCREEN_LEFT, PROJECTILE_VARIANT
    LEVEL_WAIT 4
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_A, EASY
    LEVEL_WAIT 6
    LEVEL_SPAWN BALLOON_CARRIER, SPAWN_Y_A, OFFSCREEN_RIGHT, FOLLOW_VARIANT
    LEVEL_WAIT 3
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_D - 8, EASY
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_D + 1, MEDIUM
    LEVEL_WAIT 8
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_A + 2, HARD
    LEVEL_WAIT 4
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_C + 3, EASY
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_A + 3, MEDIUM
    LEVEL_WAIT 2
    LEVEL_SPAWN BALLOON_CARRIER, SPAWN_Y_C, OFFSCREEN_RIGHT, PROJECTILE_VARIANT
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_B + 3, HARD
    LEVEL_WAIT 10
    LEVEL_SPAWN BALLOON_CARRIER, SPAWN_Y_A + 4, OFFSCREEN_LEFT, FOLLOW_VARIANT
    LEVEL_WAIT 4
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM - 4, SPAWN_X_D - 16, MEDIUM
    LEVEL_SPAWN BOMB, OFFSCREEN_BOTTOM, SPAWN_X_D - 32, EASY
    LEVEL_SPAWN BOMB, OFFSCREEN_BOTTOM, SPAWN_X_D + 4, EASY
    LEVEL_WAIT 4
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_A - 12, EASY
    LEVEL_WAIT 1
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_A - 12, EASY
    LEVEL_WAIT 1
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_D + 12, EASY
    LEVEL_SPAWN BOMB, OFFSCREEN_BOTTOM, MIDDLE_SCREEN, EASY
    LEVEL_WAIT 1
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_D + 12, EASY
    LEVEL_SPAWN BOMB, OFFSCREEN_BOTTOM, MIDDLE_SCREEN, EASY
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_B + 8, EASY
    LEVEL_WAIT 1
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_B + 8, EASY
    LEVEL_SPAWN BOMB, OFFSCREEN_BOTTOM, SPAWN_X_C + 8, EASY
    LEVEL_WAIT 2
    LEVEL_SPAWN BOMB, OFFSCREEN_BOTTOM, SPAWN_X_C + 8, EASY
    LEVEL_WAIT 10
    LEVEL_SPAWN BALLOON_CARRIER, SPAWN_Y_A + 6, OFFSCREEN_LEFT, PROJECTILE_VARIANT
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, MIDDLE_SCREEN + 4, EASY
    LEVEL_SPAWN BALLOON_CARRIER, SPAWN_Y_B + 8, OFFSCREEN_RIGHT, PROJECTILE_VARIANT
    LEVEL_WAIT 6
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_C + 8, MEDIUM
    LEVEL_WAIT 2
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_C + 2, HARD
    LEVEL_SPAWN BALLOON_CARRIER, SPAWN_Y_D - 4, OFFSCREEN_RIGHT, FOLLOW_VARIANT
    LEVEL_WAIT 8
    LEVEL_SPAWN BOMB, OFFSCREEN_BOTTOM, SPAWN_X_A, EASY
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_B, EASY
    LEVEL_WAIT 2
    LEVEL_SPAWN BOMB, OFFSCREEN_BOTTOM, SPAWN_X_C, EASY
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_D, HARD
    LEVEL_WAIT 16
    LEVEL_END

Level3:
    LEVEL_WAIT_BOSS
    LEVEL_WAIT 6
    LEVEL_END

; Desert Levels

Level4:
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_A - 8, EASY
    LEVEL_WAIT 2
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_A, EASY
    LEVEL_WAIT 8
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_B + 8, HARD
    LEVEL_WAIT 2
    LEVEL_SPAWN BIRD, SPAWN_Y_C + 8, OFFSCREEN_RIGHT, EASY
    LEVEL_SPAWN BOMB, OFFSCREEN_BOTTOM, SPAWN_X_A, EASY
    LEVEL_WAIT 8
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_B - 12, EASY
    LEVEL_SPAWN BIRD, SPAWN_Y_B, OFFSCREEN_LEFT, EASY
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_C, MEDIUM
    LEVEL_WAIT 4
    LEVEL_SPAWN BIRD, SPAWN_Y_A, OFFSCREEN_LEFT, EASY
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_C, EASY
    LEVEL_WAIT 8
    LEVEL_SPAWN BIRD, SPAWN_Y_D, OFFSCREEN_RIGHT, EASY
    LEVEL_WAIT 4
    LEVEL_SPAWN BOMB, OFFSCREEN_BOTTOM, SPAWN_X_D, MEDIUM
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_A + 5, MEDIUM
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_D + 5, EASY
    LEVEL_WAIT 4
    LEVEL_SPAWN BIRD, SPAWN_Y_A, OFFSCREEN_LEFT, EASY
    LEVEL_SPAWN BIRD, SPAWN_Y_B, OFFSCREEN_LEFT, EASY
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_B + 4, HARD
    LEVEL_WAIT 2
    LEVEL_SPAWN BOMB, OFFSCREEN_BOTTOM, SPAWN_X_A, MEDIUM
    LEVEL_SPAWN BOMB, OFFSCREEN_BOTTOM, SPAWN_X_D, MEDIUM
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_B + 8, EASY
    LEVEL_WAIT 2
    LEVEL_SPAWN BOMB, OFFSCREEN_BOTTOM, SPAWN_X_B + 8, EASY
    LEVEL_WAIT 4
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_B + 4, HARD
    LEVEL_SPAWN BIRD, SPAWN_Y_A + 5, OFFSCREEN_RIGHT, EASY
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_B + 20, HARD
    LEVEL_SPAWN BIRD, SPAWN_Y_C + 5, OFFSCREEN_RIGHT, EASY
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_B + 36, HARD
    LEVEL_WAIT 16
    LEVEL_END

Level5:
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_B, EASY
    LEVEL_WAIT 8
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_A, MEDIUM
    LEVEL_SPAWN BALLOON_CARRIER, SPAWN_Y_B, OFFSCREEN_RIGHT, PROJECTILE_VARIANT
    LEVEL_WAIT 8
    LEVEL_SPAWN BALLOON_CARRIER, SPAWN_Y_C, OFFSCREEN_LEFT, FOLLOW_VARIANT
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_C, HARD
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_D, EASY
    LEVEL_WAIT 8
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_A, EASY
    LEVEL_SPAWN BOMB, OFFSCREEN_BOTTOM, SPAWN_X_D, EASY
    LEVEL_WAIT 8
    LEVEL_SPAWN BALLOON_CARRIER, SPAWN_Y_A, OFFSCREEN_LEFT, PROJECTILE_VARIANT
    LEVEL_SPAWN BIRD, SPAWN_Y_C, OFFSCREEN_RIGHT, EASY
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_B, EASY
    LEVEL_WAIT 8
    LEVEL_SPAWN BOMB, OFFSCREEN_BOTTOM, SPAWN_X_B, MEDIUM
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_D, HARD
    LEVEL_WAIT 3
    LEVEL_SPAWN BALLOON_CARRIER, SPAWN_Y_C, OFFSCREEN_LEFT, BOMB_VARIANT
    LEVEL_WAIT 9
    LEVEL_SPAWN BIRD, SPAWN_Y_A, OFFSCREEN_LEFT, EASY
    LEVEL_SPAWN BALLOON_CARRIER, SPAWN_Y_B, OFFSCREEN_LEFT, PROJECTILE_VARIANT
    LEVEL_WAIT 8
    LEVEL_SPAWN BALLOON_CARRIER, SPAWN_Y_D, OFFSCREEN_RIGHT, FOLLOW_VARIANT
    LEVEL_WAIT 8
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM-2, SPAWN_X_A, MEDIUM
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM-6, SPAWN_X_B, EASY
    LEVEL_SPAWN BOMB, OFFSCREEN_BOTTOM, SPAWN_X_C, EASY
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM-4, SPAWN_X_D, EASY
    LEVEL_WAIT 8
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_B, HARD
    LEVEL_WAIT 3
    LEVEL_SPAWN ANVIL, OFFSCREEN_TOP, SPAWN_X_B, NONE ; TESTING
    LEVEL_WAIT 8
    LEVEL_END

Level6:
    LEVEL_WAIT_BOSS
    LEVEL_WAIT 6
    LEVEL_END

; Showdown Levels

Level7:
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_B, EASY
    LEVEL_WAIT 8
    LEVEL_WAIT 8
    LEVEL_WAIT 8
    LEVEL_WAIT 8

    LEVEL_SPAWN BALLOON_CARRIER, SPAWN_Y_C, OFFSCREEN_RIGHT, PROJECTILE_VARIANT
    LEVEL_SPAWN BALLOON_CARRIER, SPAWN_Y_A, OFFSCREEN_LEFT, PROJECTILE_VARIANT
    LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_B, EASY
    LEVEL_WAIT 8
    ; LEVEL_SPAWN BIRD, SPAWN_Y_B, OFFSCREEN_RIGHT
    ; LEVEL_WAIT 8
    ; LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_B
    ; LEVEL_SPAWN BOMB, OFFSCREEN_BOTTOM, SPAWN_X_A
    ; LEVEL_SPAWN BOMB, OFFSCREEN_BOTTOM, SPAWN_X_B
    ; LEVEL_SPAWN BOMB, OFFSCREEN_BOTTOM, SPAWN_X_C
    ; LEVEL_WAIT 8
    ; LEVEL_SPAWN BOMB, OFFSCREEN_BOTTOM, SPAWN_X_D
    ; LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_B
    ; LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_C
    ; LEVEL_WAIT 16
    ; LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_B
    ; LEVEL_WAIT 8
    ; LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_A
    ; LEVEL_SPAWN PROJECTILE_VARIANT, SPAWN_Y_B, OFFSCREEN_RIGHT
    ; LEVEL_WAIT 8
    ; LEVEL_SPAWN BALLOON_CACTUS, SPAWN_Y_C, OFFSCREEN_LEFT
    ; LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_C
    ; LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_D
    ; LEVEL_WAIT 8
    ; LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_A
    ; LEVEL_SPAWN BOMB, OFFSCREEN_BOTTOM, SPAWN_X_D
    ; LEVEL_WAIT 8
    ; LEVEL_SPAWN BALLOON_CACTUS, SPAWN_Y_A, OFFSCREEN_LEFT
    ; LEVEL_SPAWN BIRD, SPAWN_Y_C, OFFSCREEN_RIGHT
    ; LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_B
    ; LEVEL_WAIT 8
    ; LEVEL_SPAWN BOMB, OFFSCREEN_BOTTOM, SPAWN_X_B
    ; LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_D
    ; LEVEL_WAIT 8
    ; LEVEL_SPAWN BIRD, SPAWN_Y_A, OFFSCREEN_LEFT
    ; LEVEL_SPAWN BALLOON_CACTUS, SPAWN_Y_B, OFFSCREEN_LEFT
    ; LEVEL_WAIT 8
    ; LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM-2, SPAWN_X_A
    ; LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM-6, SPAWN_X_B
    ; LEVEL_SPAWN BOMB, OFFSCREEN_BOTTOM, SPAWN_X_C
    ; LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM-4, SPAWN_X_D
    ; LEVEL_WAIT 16
    ; LEVEL_SPAWN POINT_BALLOON, OFFSCREEN_BOTTOM, SPAWN_X_B
    ; LEVEL_WAIT 8
    LEVEL_WAIT 16
    LEVEL_END

Level8:
    LEVEL_END

Level9:
    LEVEL_WAIT_BOSS
    LEVEL_WAIT 6
    GAME_WON

; Handler and Initializer

InitializeNewLevel::
    xor a ; ld a, 0
    ld [wLevelWaitCounter], a
    ld [wLevelWaitBoss], a
    ld [wLevelWaitEndCounter], a

    ld a, [wLevel]
.level1:
    cp a, 1
    jr nz, .level2
    ld bc, Level1
    jr .setLevelDataAddress
.level2:
    cp a, 2
    jr nz, .level3
    ld bc, Level2
    jr .setLevelDataAddress
.level3:
    cp a, 3
    jr nz, .level4
    ld bc, Level3
    jr .setLevelDataAddress
.level4:
    cp a, 4
    jr nz, .level5
    ld bc, Level4
    jr .setLevelDataAddress
.level5:
    cp a, 5
    jr nz, .level6
    ld bc, Level5
    jr .setLevelDataAddress
.level6:
    cp a, 6
    jr nz, .level7
    ld bc, Level6
    jr .setLevelDataAddress
.level7:
    cp a, 7
    jr nz, .level8
    ld bc, Level7
    jr .setLevelDataAddress
.level8:
    cp a, 8
    jr nz, .level9
    ld bc, Level8
    jr .setLevelDataAddress
.level9:
    ld bc, Level9
.setLevelDataAddress:
    ld hl, wLevelDataAddress
    ld a, LOW(bc)
    ld [hli], a
    ld a, HIGH(bc)
    ld [hl], a
.end:
    ret

InitializeLevelVars::
    ld a, 1
    ld [wLevel], a
    call InitializeNewLevel
    ret

SpawnDataHandler:
    ; Argument hl = source address
    ld a, [hli]
    ; Update enemy number
    ldh [hEnemyNumber], a
    ld b, a
    ; Update enemy Y/X
    ld a, [hli]
    ldh [hEnemyY], a
    ld a, [hli]
    ldh [hEnemyX], a
    ld a, [hli]
    ; Update variant
    ld [hEnemyVariant], a
    ld a, b
    ; Spawns
    cp a, POINT_BALLOON
    jp z, SpawnPointBalloon
    cp a, BALLOON_CARRIER
    jp z, SpawnBalloonCarrier
    cp a, BIRD
    jp z, SpawnBird
    cp a, BOMB
    jp z, SpawnBomb
    cp a, PROJECTILE
    jp z, SpawnProjectile
    cp a, BOSS
    jp z, SpawnBoss
    cp a, BOSS_NEEDLE
    jp z, SpawnBossNeedle
    cp a, ANVIL 
    jp z, SpawnAnvil
    cp a, EXPLOSION 
    jp z, SpawnExplosion
    ret

LevelDataHandler::
    ; Frequency we read 
    ldh a, [hGlobalTimer]
    and LEVEL_UPDATE_REFRESH_TIME
    ret nz

    ; Read next level instruction
    ld a, [wLevelDataAddress]
    ld l, a
    ld a, [wLevelDataAddress+1]
    ld h, a
    ld a, [hl]

    ; Interpret
    cp a, LEVEL_SPAWN_KEY
    jr z, .spawn
    cp a, LEVEL_WAIT_KEY
    jr z, .wait
    cp a, LEVEL_WAIT_BOSS_KEY
    jr z, .waitBoss
    cp a, LEVEL_END_KEY
    jr z, .end
    cp a, GAME_WON_KEY
    jr z, .won
    ret
.spawn:
    ; Next instructions: enemy, y, x
    inc hl
    call SpawnDataHandler
    ld a, l
    ld [wLevelDataAddress], a
    ld a, h
    ld [wLevelDataAddress+1], a
    ret
.wait:
    ; Next instruction: amount to wait
    inc hl
    ld a, [wLevelWaitCounter]
    cp a, [hl]
    jr nc, .waitEnd
    inc a
    ld [wLevelWaitCounter], a
    ret
.waitEnd:
    inc hl
    ld a, l
    ld [wLevelDataAddress], a
    ld a, h
    ld [wLevelDataAddress+1], a
    xor a ; ld a, 0
    ld [wLevelWaitCounter], a
    ret
.waitBoss:
    ld a, [wLevelWaitBoss]
    cp a, 0
    jr nz, .waitBossEnd
    call BossKiller
    ret
.waitBossEnd:
    inc hl
    ld a, l
    ld [wLevelDataAddress], a
    ld a, h
    ld [wLevelDataAddress+1], a
    ret
.end:
    ldh a, [rBGP]
    cp a, 0
    jr z, .endEmptyScreen
    call InitializeInterrupts
    call InitializeEmptyPalettes
    ret
.endEmptyScreen:
    ld a, [wLevelWaitEndCounter]
    inc a 
    ld [wLevelWaitEndCounter], a
    cp a, LEVEL_WAIT_END_COUNTER
    ret nz
.incrementLevel:
    ld a, [wLevel] 
    inc a
    ld [wLevel], a 
    jp StageClear
.won:
    call FadeOutPalettes
    ret z
    jp GameWon